---
version: "2"
services:
  openweathermap_crawler:
    container_name: openweathermap_crawler
    image: ${REGISTRY}/${NAMESPACE}/${SERVICE}:${VERSION}
    environment:
      SOURCE: owm
      CLIENT: server-ubuntu
      INFLUXDBHOST: server
      INFLUXDBPORT: 12086
      INFLUXDBUSERNAME: root
      INFLUXDBPASSWORD: root
      INFLUXDBDATABASE: smarthome
      READPERIODSECONDS: 60
    restart: always


